version: '3'
services:
  shakingbot:
    image: labrie/shakingbot:latest
    container_name: shakingbot
    entrypoint: ["python", "shake.py"]
    restart: always
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
    volumes:
      - ./creds:/opt/shakingbot/creds
      
  shakingbot-tools:
    image: labrie/shakingbot:latest
    container_name: shakingbot-tools
    entrypoint: ["sleep","864000"]
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
    volumes:
      - ./creds:/opt/shakingbot/creds
